server:
  port: 8080
#
## DataBase
spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-01.cleardb.com:3306/heroku_e61a770f4088551?reconnect=true
    username: be970b473ede71
    password: 2b51098d
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
        ddl-auto: update

  ##  spring:
 ## datasource:
  ##  url: jdbc:mysql://localhost:3306/stud
  ##  username: root
  ##  password: uhbujhbq
   ## driver-class-name: com.mysql.jdbc.Driver
 ## jpa:
  ##  database: MYSQL

    ## mysql://be970b473ede71:2b51098d@eu-cdbr-west-01.cleardb.com/heroku_e61a770f4088551?reconnect=true
 ## https://app-student.herokuapp.com/student